name: Build and Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos-amd64
            CMD_BUILD: >
              PYTHONOPTIMIZE=1 pyinstaller cloud-cli.spec &&
              cd dist/ &&
              tar czf ../cloud-cli-darwin-amd64.tar.gz cloud-cli
            OUT_FILE_NAME: cloud-cli-darwin-amd64.tar.gz
          - os: macos-14
            TARGET: macos-arm64
            CMD_BUILD: >
              PYTHONOPTIMIZE=1 pyinstaller cloud-cli.spec &&
              cd dist/ &&
              tar czf ../cloud-cli-darwin-arm64.tar.gz cloud-cli
            OUT_FILE_NAME: cloud-cli-darwin-arm64.tar.gz
          - os: ubuntu-latest
            TARGET: linux-amd64
            CMD_BUILD: >
              PYTHONOPTIMIZE=1 pyinstaller cloud-cli.spec &&
              cd dist/ &&
              tar czf ../cloud-cli-linux-amd64.tar.gz cloud-cli
            OUT_FILE_NAME: cloud-cli-linux-amd64.tar.gz
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build binary
        run: ${{ matrix.CMD_BUILD }}
      - name: Generate SHA256
        run: |
          if [ "${{ runner.os }}" = "macOS" ]; then
            shasum -a 256 ${{ matrix.OUT_FILE_NAME }} > ${{ matrix.OUT_FILE_NAME }}.sha256
          else
            sha256sum ${{ matrix.OUT_FILE_NAME }} > ${{ matrix.OUT_FILE_NAME }}.sha256
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.TARGET }}
          path: |
            ${{ matrix.OUT_FILE_NAME }}
            ${{ matrix.OUT_FILE_NAME }}.sha256

  create-release:
    name: Create Release
    needs: build-and-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */cloud-cli-*.tar.gz
            */cloud-cli-*.sha256
          generate_release_notes: true

  update-brew:
    name: Update Brew Formula
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout brew tap repo
        uses: actions/checkout@v4
        with:
          repository: o37-autoforge/homebrew-cloudscript
          token: ${{ secrets.BREW_TAP_TOKEN }}
      - name: Download release artifacts and update formula
        run: |
          # Get version from tag
          VERSION=${GITHUB_REF#refs/tags/v}
          
          # Get release ID
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.BREW_TAP_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest" | \
            jq -r '.id')
          
          # Download and get SHA256 values
          ARM64_SHA256=$(curl -sL -H "Authorization: token ${{ secrets.BREW_TAP_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets" | \
            jq -r '.[] | select(.name=="cloud-cli-darwin-arm64.tar.gz.sha256").browser_download_url' | \
            xargs curl -sL | cut -d' ' -f1)
          
          AMD64_SHA256=$(curl -sL -H "Authorization: token ${{ secrets.BREW_TAP_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets" | \
            jq -r '.[] | select(.name=="cloud-cli-darwin-amd64.tar.gz.sha256").browser_download_url' | \
            xargs curl -sL | cut -d' ' -f1)
          
          LINUX_SHA256=$(curl -sL -H "Authorization: token ${{ secrets.BREW_TAP_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets" | \
            jq -r '.[] | select(.name=="cloud-cli-linux-amd64.tar.gz.sha256").browser_download_url' | \
            xargs curl -sL | cut -d' ' -f1)
          
          # Update formula file
          sed -i "s/version \".*\"/version \"$VERSION\"/" Formula/cloudscript.rb
          sed -i "s/v[0-9.]*\/cloud-cli/v$VERSION\/cloud-cli/g" Formula/cloudscript.rb
          sed -i "s/sha256 \".*\".*arm64/sha256 \"$ARM64_SHA256\"  # arm64/" Formula/cloudscript.rb
          sed -i "s/sha256 \".*\".*amd64/sha256 \"$AMD64_SHA256\"  # amd64/" Formula/cloudscript.rb
          sed -i "s/sha256 \".*\".*linux/sha256 \"$LINUX_SHA256\"  # linux/" Formula/cloudscript.rb
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Formula/cloudscript.rb
          git commit -m "Update formula to version ${GITHUB_REF#refs/tags/}"
          git push