name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos-amd64
            CMD_BUILD: >
              PYTHONOPTIMIZE=1 pyinstaller cloud-cli.spec &&
              cd dist/ &&
              tar czf ../cloud-cli-darwin-amd64.tar.gz cloud-cli
            OUT_FILE_NAME: cloud-cli-darwin-amd64.tar.gz
          - os: macos-14
            TARGET: macos-arm64
            CMD_BUILD: >
              PYTHONOPTIMIZE=1 pyinstaller cloud-cli.spec &&
              cd dist/ &&
              tar czf ../cloud-cli-darwin-arm64.tar.gz cloud-cli
            OUT_FILE_NAME: cloud-cli-darwin-arm64.tar.gz
          - os: ubuntu-latest
            TARGET: linux-amd64
            CMD_BUILD: >
              PYTHONOPTIMIZE=1 pyinstaller cloud-cli.spec &&
              cd dist/ &&
              tar czf ../cloud-cli-linux-amd64.tar.gz cloud-cli
            OUT_FILE_NAME: cloud-cli-linux-amd64.tar.gz

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Build binary
        run: ${{ matrix.CMD_BUILD }}
        
      - name: Generate SHA256
        run: |
          sha256sum ${{ matrix.OUT_FILE_NAME }} > ${{ matrix.OUT_FILE_NAME }}.sha256
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.TARGET }}
          path: |
            ${{ matrix.OUT_FILE_NAME }}
            ${{ matrix.OUT_FILE_NAME }}.sha256

  create-release:
    name: Create Release
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */cloud-cli-*.tar.gz
            */cloud-cli-*.sha256
          generate_release_notes: true