name: Update Brew Formula
on:
  release:
    types: [published]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout brew tap repo
        uses: actions/checkout@v4
        with:
          repository: Panchangam18/test-cloudscript-brew
          token: ${{ secrets.BREW_TAP_TOKEN }} 

      - name: Download release artifacts and update formula
        run: |
          # Get version from release tag
          VERSION="${{ github.event.release.tag_name }}"
          VERSION=${VERSION#v}  # Remove 'v' prefix
          
          # Download and get SHA256 values
          ARM64_SHA256=$(curl -sL "${{ github.event.release.assets_url }}" | \
            jq -r '.[] | select(.name=="cloud-cli-darwin-arm64.tar.gz.sha256").browser_download_url' | \
            xargs curl -sL | cut -d' ' -f1)
          
          AMD64_SHA256=$(curl -sL "${{ github.event.release.assets_url }}" | \
            jq -r '.[] | select(.name=="cloud-cli-darwin-amd64.tar.gz.sha256").browser_download_url' | \
            xargs curl -sL | cut -d' ' -f1)
          
          LINUX_SHA256=$(curl -sL "${{ github.event.release.assets_url }}" | \
            jq -r '.[] | select(.name=="cloud-cli-linux-amd64.tar.gz.sha256").browser_download_url' | \
            xargs curl -sL | cut -d' ' -f1)
          
          # Update formula file
          sed -i "s/version \".*\"/version \"$VERSION\"/" Formula/cloudscript.rb
          sed -i "s/v[0-9.]*\/cloud-cli/v$VERSION\/cloud-cli/g" Formula/cloudscript.rb
          sed -i "s/sha256 \".*\".*arm64/sha256 \"$ARM64_SHA256\"  # arm64/" Formula/cloudscript.rb
          sed -i "s/sha256 \".*\".*amd64/sha256 \"$AMD64_SHA256\"  # amd64/" Formula/cloudscript.rb
          sed -i "s/sha256 \".*\".*linux/sha256 \"$LINUX_SHA256\"  # linux/" Formula/cloudscript.rb

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Formula/cloudscript.rb
          git commit -m "Update formula to version ${{ github.event.release.tag_name }}"
          git push